<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kategori Campaign</name>
   <tag></tag>
   <elementGuidId>908584ff-a4c0-4a41-8716-975748fdae65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sliding-menu']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>367dab80-d6e3-479d-80ff-1a6de3390a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.danaeveryday.id/campaign_category</value>
      <webElementGuid>dc57a94a-ee8c-4d29-938e-f383ca73af5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori Campaign</value>
      <webElementGuid>5088ee99-b9f5-4e47-aa77-e5853ebff828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sliding-menu&quot;)/ul[@class=&quot;smenu&quot;]/li[4]/a[1]</value>
      <webElementGuid>2281c868-58b9-472c-b620-c4c7a591e1db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sliding-menu']/ul/li[4]/a</value>
      <webElementGuid>64bf6bc7-d4ef-418e-ac56-ad442d0bdb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kategori Campaign')]</value>
      <webElementGuid>22a9559b-acbc-4479-b214-595320a09f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Campaign'])[1]/following::a[1]</value>
      <webElementGuid>038ca1d4-30c1-49fc-840d-849d6096be57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Dana Everyday'])[1]/following::a[2]</value>
      <webElementGuid>9b22092b-f8ba-4856-99a4-ff719a983aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::a[1]</value>
      <webElementGuid>35df1860-d699-42b9-aac4-5cee1b4754e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat Dan Ketentuan'])[1]/preceding::a[2]</value>
      <webElementGuid>922e84d3-8649-40cb-b80f-6d518f64644b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kategori Campaign']/parent::*</value>
      <webElementGuid>e7ca1eef-c3bf-4d82-8044-071ae017157e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.danaeveryday.id/campaign_category')]</value>
      <webElementGuid>79c21118-d411-43c3-a61c-3148ad1f992c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>82751e80-e26f-46b8-9912-b174d7fe117e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.danaeveryday.id/campaign_category' and (text() = 'Kategori Campaign' or . = 'Kategori Campaign')]</value>
      <webElementGuid>76885288-154d-4f8d-ae69-e102d8f2c6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
