<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGIN</name>
   <tag></tag>
   <elementGuidId>2455198e-ef35-4372-a070-ee932168f605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login_form']/div[3]/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button--wayra.pull-right.btn-donation-detail.xs-m20.btnLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9956b6fc-8f8b-4cd0-b748-3529a6a0ef71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--wayra pull-right btn-donation-detail xs-m20 btnLogin</value>
      <webElementGuid>7866f9c2-2ec7-4b39-9516-7ddca8d017e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>4c0d3fe7-1986-4dea-a50a-8beacccbda6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-xs-12 col-sm-6&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;button button--wayra pull-right btn-donation-detail xs-m20 btnLogin&quot;]</value>
      <webElementGuid>acdd8c22-b05c-4010-ab81-30ecc4ad9dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[3]/div[2]/div/button</value>
      <webElementGuid>828e52d2-efa2-4a94-92dc-e26a39932dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar akun'])[1]/following::button[1]</value>
      <webElementGuid>1a42cf75-a78b-4ecc-89ce-7f8afab197a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::button[1]</value>
      <webElementGuid>1bf86620-d4ca-4e74-9db8-d6444a222965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat Datang!'])[2]/preceding::button[3]</value>
      <webElementGuid>2cc042ac-dbfd-4766-bf7a-69826cb044e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/preceding::button[3]</value>
      <webElementGuid>b59f9f11-ddb9-4bc2-a9d7-8c6f3f6d52cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>65404623-ae7d-47a7-add5-8bd3530ce295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>038be096-9330-4f07-ba3b-69e9e2c1fc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>be4b5916-f6d8-430e-9997-89b2e6a7e3d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
