<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Galang Dana_fa fa-sign-out</name>
   <tag></tag>
   <elementGuidId>072f27d6-964b-4b5d-a469-0755251c735a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-sign-out</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ee1b03a7-6a4b-474d-b935-c34d1251ddce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-sign-out</value>
      <webElementGuid>a3ca33f5-54f2-4f4d-b1c7-ca5b18892ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row inline min-10&quot;]/div[@class=&quot;col inline l-4 m-5 s-7 text-right min-10&quot;]/div[@class=&quot;box-donasi&quot;]/div[@class=&quot;tbl&quot;]/div[@class=&quot;cell&quot;]/a[@class=&quot;pointer hidden-xs&quot;]/div[@class=&quot;in-donasi login white-bg&quot;]/div[@class=&quot;login-icon&quot;]/i[@class=&quot;fa fa-sign-out&quot;]</value>
      <webElementGuid>980ed6df-5e29-4f31-af71-499c1a18afcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/i</value>
      <webElementGuid>7d800a34-220e-4f01-a1eb-2b183e90a186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
