<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_member_password</name>
   <tag></tag>
   <elementGuidId>6191ab3a-4fa2-47d4-8119-9e3d96e25490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='member_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;member_password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b46a613-f04c-437a-b449-57ba0982f383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f9c58698-ed0b-4a27-be67-71c3068cc518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ade470c0-c782-4d0a-ba88-ace1b60f3c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_password</value>
      <webElementGuid>847e4711-0801-48b4-8c9a-724200986cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e80e5818-6cda-43c9-bda7-adc91230ebf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_form&quot;)/div[@class=&quot;row inline&quot;]/div[@class=&quot;col inline l-12 m-12 s-12&quot;]/div[@class=&quot;form-group&quot;]/p[@class=&quot;filled-text&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>08b28972-929c-40b9-9994-ff43f4739828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='member_password']</value>
      <webElementGuid>9c74b7a8-a399-4787-aa64-a748b4d63a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[2]/div/div/p/input</value>
      <webElementGuid>9dc904af-3e50-49db-b944-9a7043d8faf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p/input</value>
      <webElementGuid>b13d9591-8aa2-4739-a3ba-239031b20b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'member_password']</value>
      <webElementGuid>e0045d92-447b-4ceb-aff8-997668204534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
