<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UPDATE PROFILE</name>
   <tag></tag>
   <elementGuidId>0967a5f4-2c34-4aff-a450-82395f9f614c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='message_submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;message_submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc433447-47c6-4d13-a607-f787df978402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--wayra send-message btn-update-profile</value>
      <webElementGuid>86fd86b7-2883-45eb-9b67-a99c12045a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7240477e-6400-4c56-9fa7-fd2698f826dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message_submit</value>
      <webElementGuid>664b855a-cbd2-48ba-9ff7-a2e27e6a0e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UPDATE PROFILE</value>
      <webElementGuid>798d4815-0fe1-442f-bb2d-89d1a52b57cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 text-center&quot;]/button[@class=&quot;button button--wayra send-message btn-update-profile&quot;]</value>
      <webElementGuid>5e6b1c5c-a67e-416b-81f1-a655c23e8b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='message_submit']</value>
      <webElementGuid>a811ba07-3b80-48a6-b4b9-83cca5bbd8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_form']/div[6]/div/button</value>
      <webElementGuid>1def61b2-908a-49b2-8da3-30161b98da62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[2]/following::button[1]</value>
      <webElementGuid>b3379380-43d8-4de7-8fd6-d4c72c5da96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Password'])[1]/following::button[1]</value>
      <webElementGuid>ef77e5fc-387a-4b9d-b977-9ac16f4b8eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>ef03b653-bd2e-4595-b24f-b0fcda34fb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donasi'])[3]/preceding::button[1]</value>
      <webElementGuid>1c199466-8eea-4d3e-8f7f-abb89d9cc5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UPDATE PROFILE']/parent::*</value>
      <webElementGuid>cfa8b8a5-c2c8-47c4-a523-d5d42078db65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/form/div[6]/div/button</value>
      <webElementGuid>dd454569-2ccf-4bf2-8700-20c6d0118365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'message_submit' and (text() = 'UPDATE PROFILE' or . = 'UPDATE PROFILE')]</value>
      <webElementGuid>06cebda4-3d37-4c9c-b54c-1f4b27a282fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
