<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_member_phone</name>
   <tag></tag>
   <elementGuidId>77916527-32c9-4096-a1b8-847b6bcfeee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @name = 'member_phone']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='member_phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-5.col-md-offset-1 > div.form-group > p > input[name=&quot;member_phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc30b2f7-b430-449b-a316-a5ff97841147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-focus pt14</value>
      <webElementGuid>dbbbeef4-b260-47eb-b123-c95cd0a92af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1f494067-3810-4032-a0a2-8c3d31ab5978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>member_phone</value>
      <webElementGuid>c754736d-aaa9-49c4-8a4f-72200141e519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>087868854658</value>
      <webElementGuid>db53b72f-8b5a-4471-b83b-aa63eba1d96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 col-md-offset-1&quot;]/div[@class=&quot;form-group&quot;]/p[1]/input[@class=&quot;form-control-focus pt14&quot;]</value>
      <webElementGuid>0a27bd04-bddc-43dd-aeb1-cff1e39e2491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='member_phone'])[2]</value>
      <webElementGuid>225250d3-6053-4211-9834-9a7bf9263699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_form']/div[2]/div[2]/div/p/input</value>
      <webElementGuid>faa0b4aa-7e52-4e91-a9d6-2f1197b0f5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/p/input</value>
      <webElementGuid>1707a799-629d-44ed-a9d2-30150048feb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'member_phone']</value>
      <webElementGuid>c6157aee-4fd4-4eb0-b5ed-9c99ce7e9a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
